name: Release

on:
  push:
    branches:
      - main

env:
  GOOGLE_CLOUD_REGION: "asia-northeast1"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDP }}
          service_account: "sa-github@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker
        run: gcloud auth configure-docker ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: sha
        name: Set GitHub shorted SHA
        run: echo "sha_short=$( git rev-parse --short HEAD )" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          tags: ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/workstations/customized:${{ steps.sha.outputs.sha_short }}
          context: .
          push: true

      - name: Create a workstation
        run: |
          gcloud workstations configs create vscode-customized-${{ steps.sha.outputs.sha_short }} \
            --region ${{ env.GOOGLE_CLOUD_REGION }} --cluster ${{ secrets.CLOUD_WORKSTATIONS_CLUSTER }} --machine-type e2-standard-4 \
            --container-custom-image ${{ env.GOOGLE_CLOUD_REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT }}/workstations/customized:${{ steps.sha.outputs.sha_short }} \
            --idle-timeout 3600 --running-timeout 43200 --max-usable-workstations-count 1 \
            --service-account sa-workstations@${{ secrets.GOOGLE_CLOUD_PROJECT }}.iam.gserviceaccount.com \
            --shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring
          gcloud workstations create vscode-${{ steps.sha.outputs.sha_short }} --async --region ${{ env.GOOGLE_CLOUD_REGION }} \
            --cluster ${{ secrets.CLOUD_WORKSTATIONS_CLUSTER }} --config vscode-customized-${{ steps.sha.outputs.sha_short }}
